---
- name: Ensure VM modification job templates exist
  ansible.builtin.include_tasks: job_templates.yml

- name: Ensure Modify VM CPUs workflow exists
  ansible.builtin.include_tasks: workflow_cpu.yml

- name: Ensure Modify VM Memory workflow exists
  ansible.builtin.include_tasks: workflow_memory.yml
