---
- name: Ensure Basic Event Stream credential exists in EDA
  ansible.eda.credential:
    name: "{{ aap_eda_pipeline_event_stream_credential }}"
    description: Basic auth for Alertmanager webhook to EDA event stream
    credential_type_name: Basic Event Stream
    organization_name: "{{ aap_eda_pipeline_organization }}"
    inputs:
      username: "{{ aap_eda_pipeline_event_stream_username }}"
      password: "{{ aap_eda_pipeline_event_stream_password }}"
    state: present
    controller_host: "{{ aap_eda_pipeline_controller_host }}"
    controller_token: "{{ aap_eda_pipeline_controller_oauthtoken }}"
    validate_certs: "{{ aap_eda_pipeline_validate_certs }}"
  register: aap_eda_pipeline_event_stream_credential_result
  no_log: true

- name: Ensure Gitea SCM credential exists in EDA
  ansible.eda.credential:
    name: "{{ aap_eda_pipeline_gitea_credential }}"
    description: Gitea credentials for Rulebooks SCM project
    credential_type_name: Source Control
    organization_name: "{{ aap_eda_pipeline_organization }}"
    inputs:
      username: "{{ demo_platform.gitea.username }}"
      password: "{{ demo_platform.gitea.password }}"
    state: present
    controller_host: "{{ aap_eda_pipeline_controller_host }}"
    controller_token: "{{ aap_eda_pipeline_controller_oauthtoken }}"
    validate_certs: "{{ aap_eda_pipeline_validate_certs }}"
  register: aap_eda_pipeline_gitea_credential_result
  no_log: true

- name: Ensure AAP Controller credential exists in EDA
  ansible.eda.credential:
    name: "{{ aap_eda_pipeline_controller_credential }}"
    description: OAuth token for EDA rulebook to launch AAP job templates
    credential_type_name: Red Hat Ansible Automation Platform
    organization_name: "{{ aap_eda_pipeline_organization }}"
    inputs:
      host: >-
        {{
          (aap_eda_pipeline_controller_host | regex_replace('/$', ''))
          ~ (aap_eda_pipeline_controller_credential_host_suffix | default('/api/controller/'))
        }}
      oauth_token: "{{ aap_eda_pipeline_controller_oauthtoken }}"
      verify_ssl: "{{ aap_eda_pipeline_validate_certs | bool }}"
    state: present
    controller_host: "{{ aap_eda_pipeline_controller_host }}"
    controller_token: "{{ aap_eda_pipeline_controller_oauthtoken }}"
    validate_certs: "{{ aap_eda_pipeline_validate_certs }}"
  register: aap_eda_pipeline_controller_credential_result
  no_log: true
