---
- name: Ensure AIOps Localhost inventory exists in AAP
  awx.awx.inventory:
    name: "{{ aap_vm_pipeline_inventory }}"
    organization: "{{ aap_vm_pipeline_organization }}"
    state: present
    controller_host: "{{ aap_vm_pipeline_controller_host }}"
    controller_oauthtoken: "{{ aap_vm_pipeline_controller_oauthtoken }}"
    validate_certs: "{{ aap_vm_pipeline_validate_certs }}"

- name: Ensure localhost host exists in AIOps Localhost inventory
  awx.awx.host:
    name: localhost
    inventory: "{{ aap_vm_pipeline_inventory }}"
    state: present
    variables:
      ansible_connection: local
    controller_host: "{{ aap_vm_pipeline_controller_host }}"
    controller_oauthtoken: "{{ aap_vm_pipeline_controller_oauthtoken }}"
    validate_certs: "{{ aap_vm_pipeline_validate_certs }}"
