---
- name: Ensure Push VM Manifest job template exists in AAP
  awx.awx.job_template:
    name: "{{ aap_vm_pipeline_jt_push_vm }}"
    organization: "{{ aap_vm_pipeline_organization }}"
    project: "{{ aap_vm_pipeline_project }}"
    inventory: "{{ aap_vm_pipeline_inventory }}"
    playbook: "{{ aap_vm_pipeline_playbook_push }}"
    job_type: run
    state: present
    survey_enabled: false
    extra_vars: "{{ aap_vm_pipeline_job_extra_vars }}"
    ask_variables_on_launch: true
    credentials:
      - "{{ aap_vm_pipeline_credential_openshift }}"
      - "{{ aap_vm_pipeline_credential_gitea }}"
      - "{{ aap_vm_pipeline_credential_itsm }}"
      - "{{ aap_vm_pipeline_credential_aap }}"
    controller_host: "{{ aap_vm_pipeline_controller_host }}"
    controller_oauthtoken: "{{ aap_vm_pipeline_controller_oauthtoken }}"
    validate_certs: "{{ aap_vm_pipeline_validate_certs }}"
  no_log: true

- name: Ensure Sync Infrastructure VMs job template exists in AAP
  awx.awx.job_template:
    name: "{{ aap_vm_pipeline_jt_sync_vms }}"
    organization: "{{ aap_vm_pipeline_organization }}"
    project: "{{ aap_vm_pipeline_project }}"
    inventory: "{{ aap_vm_pipeline_inventory }}"
    playbook: "{{ aap_vm_pipeline_playbook_sync }}"
    job_type: run
    state: present
    extra_vars: "{{ aap_itsm_job_template_extra_vars }}"
    ask_variables_on_launch: true
    credentials:
      - "{{ aap_vm_pipeline_credential_openshift }}"
      - "{{ aap_vm_pipeline_credential_gitea }}"
      - "{{ aap_vm_pipeline_credential_itsm }}"
      - "{{ aap_vm_pipeline_credential_aap }}"
    controller_host: "{{ aap_vm_pipeline_controller_host }}"
    controller_oauthtoken: "{{ aap_vm_pipeline_controller_oauthtoken }}"
    validate_certs: "{{ aap_vm_pipeline_validate_certs }}"

- name: Ensure Register ITSM VM Asset job template exists in AAP
  awx.awx.job_template:
    name: "{{ aap_vm_pipeline_jt_register_itsm }}"
    organization: "{{ aap_vm_pipeline_organization }}"
    project: "{{ aap_vm_pipeline_project }}"
    inventory: "{{ aap_vm_pipeline_inventory }}"
    playbook: "{{ aap_vm_pipeline_playbook_register_itsm }}"
    job_type: run
    state: present
    extra_vars: "{{ aap_register_itsm_vm_asset_job_extra_vars }}"
    ask_variables_on_launch: true
    credentials:
      - "{{ aap_vm_pipeline_credential_itsm }}"
      - "{{ aap_vm_pipeline_credential_openshift }}"
      - "{{ aap_vm_pipeline_credential_aap }}"
    controller_host: "{{ aap_vm_pipeline_controller_host }}"
    controller_oauthtoken: "{{ aap_vm_pipeline_controller_oauthtoken }}"
    validate_certs: "{{ aap_vm_pipeline_validate_certs }}"
