---
- name: Ensure Gitea SCM credential exists in AAP
  awx.awx.credential:
    name: "{{ aap_vm_pipeline_credential_gitea_scm }}"
    organization: "{{ aap_vm_pipeline_organization }}"
    credential_type: Source Control
    state: present
    inputs:
      username: "{{ demo_platform.gitea.username }}"
      password: "{{ demo_platform.gitea.password }}"
    controller_host: "{{ aap_vm_pipeline_controller_host }}"
    controller_oauthtoken: "{{ aap_vm_pipeline_controller_oauthtoken }}"
    validate_certs: "{{ aap_vm_pipeline_validate_certs }}"
  no_log: true
