---
- name: Ensure Create Apache Alert Incident job template exists in AAP
  awx.awx.job_template:
    name: "{{ aap_apache_troubleshoot_pipeline_jt_create_incident }}"
    organization: "{{ aap_apache_troubleshoot_pipeline_organization }}"
    project: "{{ aap_apache_troubleshoot_pipeline_project }}"
    inventory: "{{ aap_apache_troubleshoot_pipeline_inventory }}"
    playbook: "{{ aap_apache_troubleshoot_pipeline_playbook_create_incident }}"
    job_type: run
    state: present
    survey_enabled: false
    extra_vars: "{{ aap_apache_troubleshoot_pipeline_job_extra_vars_create }}"
    ask_variables_on_launch: true
    credentials:
      - "{{ aap_apache_troubleshoot_pipeline_credential_itsm }}"
      - "{{ aap_apache_troubleshoot_pipeline_credential_aap }}"
    controller_host: "{{ aap_apache_troubleshoot_pipeline_controller_host }}"
    controller_oauthtoken: "{{ aap_apache_troubleshoot_pipeline_controller_oauthtoken }}"
    validate_certs: "{{ aap_apache_troubleshoot_pipeline_validate_certs }}"

- name: Ensure Troubleshoot apache application job template exists in AAP
  awx.awx.job_template:
    name: "{{ aap_apache_troubleshoot_pipeline_jt_troubleshoot }}"
    organization: "{{ aap_apache_troubleshoot_pipeline_organization }}"
    project: "{{ aap_apache_troubleshoot_pipeline_project }}"
    inventory: "{{ aap_apache_troubleshoot_pipeline_inventory }}"
    playbook: "{{ aap_apache_troubleshoot_pipeline_playbook_troubleshoot }}"
    job_type: run
    state: present
    survey_enabled: false
    extra_vars: >-
      {{
        aap_apache_troubleshoot_pipeline_job_extra_vars_troubleshoot
        | combine({'chat_webhook_url': aap_apache_troubleshoot_chat_webhook_url}, recursive=True)
      }}
    ask_variables_on_launch: true
    credentials:
      - "{{ aap_apache_troubleshoot_pipeline_credential_vms }}"
      - "{{ aap_apache_troubleshoot_pipeline_credential_itsm }}"
      - "{{ aap_apache_troubleshoot_pipeline_credential_chat }}"
      - "{{ aap_apache_troubleshoot_pipeline_credential_aap }}"
      - "{{ aap_apache_troubleshoot_pipeline_credential_gitea }}"
      - "{{ aap_apache_troubleshoot_pipeline_credential_openshift }}"
    controller_host: "{{ aap_apache_troubleshoot_pipeline_controller_host }}"
    controller_oauthtoken: "{{ aap_apache_troubleshoot_pipeline_controller_oauthtoken }}"
    validate_certs: "{{ aap_apache_troubleshoot_pipeline_validate_certs }}"
