---
- name: Resolve dynamic remediation job template ID
  ansible.builtin.set_fact:
    lightspeed_remediation_dynamic_jt_id: >-
      {{
        lightspeed_remediation_jt_create.json.id
        if (lightspeed_remediation_jt_lookup.json.count | default(0) == 0)
        else lightspeed_remediation_jt_lookup.json.results[0].id
      }}

- name: Lookup credentials currently associated with dynamic remediation job template
  ansible.builtin.uri:
    url: >-
      {{ aap_controller_host }}/api/controller/v2/job_templates/{{
      lightspeed_remediation_dynamic_jt_id }}/credentials/
    method: GET
    headers:
      Authorization: "Bearer {{ lightspeed_remediation_controller_oauthtoken }}"
    validate_certs: false
    status_code: 200
  register: lightspeed_remediation_jt_current_credentials

- name: Disassociate credentials not required for dynamic remediation job template
  ansible.builtin.uri:
    url: >-
      {{ aap_controller_host }}/api/controller/v2/job_templates/{{
      lightspeed_remediation_dynamic_jt_id }}/credentials/
    method: POST
    headers:
      Authorization: "Bearer {{ lightspeed_remediation_controller_oauthtoken }}"
      Content-Type: application/json
    validate_certs: false
    body_format: json
    body:
      id: "{{ item.id }}"
      disassociate: true
    status_code: [201, 204]
  loop: "{{ lightspeed_remediation_jt_current_credentials.json.results }}"
  when: item.id not in lightspeed_remediation_credential_ids

- name: Associate Virtual Machines credential with dynamic remediation job template
  ansible.builtin.uri:
    url: >-
      {{ aap_controller_host }}/api/controller/v2/job_templates/{{
      lightspeed_remediation_dynamic_jt_id }}/credentials/
    method: POST
    headers:
      Authorization: "Bearer {{ lightspeed_remediation_controller_oauthtoken }}"
      Content-Type: application/json
    validate_certs: false
    body_format: json
    body:
      id: "{{ item }}"
      associate: true
    status_code: [201, 204]
  loop: "{{ lightspeed_remediation_credential_ids }}"
  when: item not in (lightspeed_remediation_jt_current_credentials.json.results | map(attribute='id') | list)
