---
aap_generic_app_delete_pipeline_organization: AIOps
aap_generic_app_delete_pipeline_validate_certs: false
aap_generic_app_delete_pipeline_controller_api_prefix: /api/controller/

aap_generic_app_delete_pipeline_inventory: AIOps Localhost
aap_generic_app_delete_pipeline_project: AIOps Playbooks
aap_generic_app_delete_pipeline_workflow: Delete Generic Application Stack

aap_generic_app_delete_pipeline_jt_delete_probe: Delete Generic Application HTTP Probe
aap_generic_app_delete_pipeline_jt_delete_manifest: Delete VM Manifest
aap_generic_app_delete_pipeline_jt_delete_itsm_app: Delete ITSM Generic Application Asset
aap_generic_app_delete_pipeline_jt_delete_itsm_vm: Delete ITSM VM Asset

aap_generic_app_delete_pipeline_playbook_delete_probe: delete_generic_app_http_probe.yml
aap_generic_app_delete_pipeline_playbook_delete_manifest: delete_vm_manifest.yml
aap_generic_app_delete_pipeline_playbook_delete_itsm_app: delete_itsm_generic_app_asset.yml
aap_generic_app_delete_pipeline_playbook_delete_itsm_vm: delete_itsm_vm_asset.yml
