---
gitops_infrastructure_app_name: infrastructure-vms
gitops_infrastructure_app_namespace: openshift-gitops
gitops_infrastructure_argocd_project: default
gitops_infrastructure_gitea_repo: Infrastructure
gitops_infrastructure_source_path: vms
gitops_infrastructure_source_branch: main
gitops_infrastructure_repo_secret_name: gitea-infrastructure
gitops_infrastructure_validate_certs: false
gitops_infrastructure_gitea_insecure: true
gitops_infrastructure_automated_allow_empty: true
