---
openshift_generic_app_monitoring_namespace: aiops-demo
openshift_generic_app_monitoring_alert_name: GenericApplicationDown
openshift_generic_app_monitoring_probe_job: generic-app-http
openshift_generic_app_monitoring_probe_for: 30s
openshift_generic_app_monitoring_probe_interval: 15s
openshift_generic_app_monitoring_blackbox_image: quay.io/prometheus/blackbox-exporter:v0.25.0
openshift_generic_app_monitoring_blackbox_prober: blackbox-exporter.aiops-demo.svc:9115
openshift_generic_app_monitoring_alertmanager_config_name: generic-app-alert-to-eda
openshift_generic_app_monitoring_prometheus_rule_name: generic-app-http-probes
openshift_generic_app_monitoring_eda_webhook_secret_name: eda-generic-app-alert-webhook
openshift_generic_app_monitoring_eda_webhook_use_internal: true
openshift_generic_app_monitoring_eda_event_stream_internal_service: ansible-eda-event-stream.aap.svc.cluster.local:8000
openshift_generic_app_monitoring_alertmanager_group_wait: 10s
openshift_generic_app_monitoring_alertmanager_group_interval: 1m
openshift_generic_app_monitoring_alertmanager_repeat_interval: 5m
openshift_generic_app_monitoring_uwm_alertmanager_namespace: openshift-user-workload-monitoring
openshift_generic_app_monitoring_uwm_alertmanager_container: alertmanager
openshift_generic_app_monitoring_delete_silence_minutes: 5
openshift_generic_app_monitoring_require_uwm: true
openshift_generic_app_monitoring_enable_uwm: true
openshift_generic_app_monitoring_uwm_wait_retries: 60
openshift_generic_app_monitoring_uwm_wait_delay: 15
