---
openshift_apache_monitoring_namespace: aiops-demo
openshift_apache_monitoring_alert_name: ApacheApplicationDown
openshift_apache_monitoring_probe_job: apache-http
openshift_apache_monitoring_probe_for: 30s
openshift_apache_monitoring_probe_interval: 15s
openshift_apache_monitoring_blackbox_image: quay.io/prometheus/blackbox-exporter:v0.25.0
openshift_apache_monitoring_blackbox_prober: blackbox-exporter.aiops-demo.svc:9115
openshift_apache_monitoring_alertmanager_config_name: apache-alert-to-eda
openshift_apache_monitoring_prometheus_rule_name: apache-http-probes
openshift_apache_monitoring_eda_webhook_secret_name: eda-apache-alert-webhook
openshift_apache_monitoring_require_uwm: true
openshift_apache_monitoring_enable_uwm: true
openshift_apache_monitoring_uwm_wait_retries: 60
openshift_apache_monitoring_uwm_wait_delay: 15
