---
- name: Remove AlertmanagerConfig for Generic Application alerts
  kubernetes.core.k8s:
    state: absent
    api_version: monitoring.coreos.com/v1alpha1
    kind: AlertmanagerConfig
    name: "{{ openshift_generic_app_monitoring_alertmanager_config_name }}"
    namespace: "{{ openshift_generic_app_monitoring_namespace }}"
  ignore_errors: true

- name: Remove PrometheusRule for Generic Application HTTP probes
  kubernetes.core.k8s:
    state: absent
    api_version: monitoring.coreos.com/v1
    kind: PrometheusRule
    name: "{{ openshift_generic_app_monitoring_prometheus_rule_name }}"
    namespace: "{{ openshift_generic_app_monitoring_namespace }}"
  ignore_errors: true

- name: Remove Alertmanager webhook basic auth Secret
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Secret
    name: "{{ openshift_generic_app_monitoring_eda_webhook_secret_name }}"
    namespace: "{{ openshift_generic_app_monitoring_namespace }}"
  ignore_errors: true
