---
image: quay.io/zaskan/fedora-cloud-containerdisk:v43
vm_namespace: aiops-demo
ssh_secret_name: authorized-keys
gitops_infrastructure_dest_namespace: "{{ vm_namespace }}"

gitops_infrastructure_app_name: infrastructure-vms
gitops_infrastructure_app_namespace: openshift-gitops
gitops_infrastructure_argocd_project: default
gitops_infrastructure_gitea_repo: Infrastructure
gitops_infrastructure_source_path: vms
gitops_infrastructure_source_branch: main
gitops_infrastructure_repo_secret_name: gitea-infrastructure
gitops_infrastructure_validate_certs: false
gitops_infrastructure_gitea_insecure: true

generic_app_default_packages:
  - httpd
  - git
generic_app_default_clone_path: /var/www/html
generic_app_default_service: httpd
generic_app_default_branch: main
generic_app_validate_certs: false

app_exposure_route_wait_retries: 30
app_exposure_route_wait_delay: 10

openshift_generic_app_monitoring_probe_job: generic-app-http
openshift_generic_app_monitoring_probe_interval: 15s
openshift_generic_app_monitoring_blackbox_prober: blackbox-exporter.aiops-demo.svc:9115
openshift_generic_app_monitoring_alert_name: GenericApplicationDown
openshift_generic_app_monitoring_uwm_alertmanager_namespace: openshift-user-workload-monitoring
openshift_generic_app_monitoring_uwm_alertmanager_container: alertmanager
openshift_generic_app_monitoring_delete_silence_minutes: 5

itsm_generic_app_asset_type_name: Generic Application
itsm_generic_app_stack_request_template_name: Generic Application Stack

chat_aiops_channel_name: operations

generic_app_incident_remediation_post_chat_summary: true

generic_app_delete_post_chat_summary: true

vm_modification_post_chat_summary: false

openshift_cluster_domain: apps.ocp.zaskan.es

vm_ip_pool_start: 192.168.100.100
vm_ip_pool_end: 192.168.100.250
vm_ip_prefix_length: 24
vm_ip_annotation: aiops.io/ip-address
vm_udn_name: aiops-vm-network
vm_udn_pod_interface: net1
vm_primary_guest_interface: enp1s0
vm_secondary_guest_interface: enp2s0
