---
- name: Load OpenShift credentials for HTTP Probe apply
  ansible.builtin.include_tasks: ../common/tasks/load_openshift_credential.yml

- name: Apply HTTP Probe for Generic Application monitoring outside GitOps
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'generic_app_http_probe.yaml.j2') | from_yaml }}"
    host: "{{ openshift_credential_host | default(omit) }}"
    api_key: "{{ openshift_credential_token | default(omit) }}"
    validate_certs: false
