---
- name: Ensure Argo CD repository secret for Gitea Infrastructure exists
  kubernetes.core.k8s:
    state: present
    host: "{{ gitops_infrastructure_openshift_api_server | default(omit) }}"
    api_key: "{{ gitops_infrastructure_openshift_token | default(omit) }}"
    validate_certs: "{{ gitops_infrastructure_validate_certs }}"
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ gitops_infrastructure_repo_secret_name }}"
        namespace: "{{ gitops_infrastructure_app_namespace }}"
        labels:
          argocd.argoproj.io/secret-type: repository
      type: Opaque
      stringData:
        type: git
        url: "{{ gitops_infrastructure_repo_url }}"
        username: "{{ gitops_infrastructure_gitea_username }}"
        password: "{{ gitops_infrastructure_gitea_password }}"
        insecure: "{{ gitops_infrastructure_gitea_insecure | bool | ternary('true', 'false') }}"
  no_log: true
