---
- name: Ensure aiops-observability namespace exists
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ observability_kit_namespace }}"
        labels:
          app.kubernetes.io/part-of: aiops-observability
          argocd.argoproj.io/managed-by: >-
            {{ gitops_observability_argocd_instance_name | default('openshift-gitops') }}
