---
itsm_change_task_final_ctask_title: AAP — Start application service
itsm_change_task_completion_summary_heading: Generic Application stack deployment complete.

itsm_change_task_ctask_title_install_httpd: AAP — Install application packages
itsm_change_task_ctask_title_deploy_app: AAP — Deploy application repository
itsm_change_task_ctask_title_expose_apache: AAP — Expose application
itsm_change_task_ctask_title_start_httpd: AAP — Start application service
