---
- name: Install httpd on target server
  hosts: "{{ target_host }}"
  gather_facts: true
  become: true
  vars_files:
    - defaults/main.yml
  tasks:
    - name: Install httpd and git packages on target host
      ansible.builtin.include_role:
        name: apache_app
        tasks_from: install
