---
- name: Launch Lightspeed remediation job template in AAP
  hosts: localhost
  gather_facts: false
  vars_files:
    - defaults/main.yml
  tasks:
    - name: Launch dynamic remediation job template and wait for success
      ansible.builtin.include_role:
        name: lightspeed_remediation
        tasks_from: launch_job_template.yml
