---
- name: OpenShift + AAP demo install
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../group_vars/all/demo_platform.yml
    - ../group_vars/all/aap_casc.yml
    - ../group_vars/all/gitea_repos.yml
    - ../group_vars/all/aap_vm_pipeline.yml
    - ../group_vars/all/aap_httpd_pipeline.yml
  roles:
    - role: demo_platform
