---
- name: Uninstall demo applications from OpenShift
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../group_vars/all/demo_platform.yml
    - ../group_vars/all/aap_uninstall.yml
    - ../group_vars/all/aap_casc.yml
    - ../group_vars/all/aap_vm_pipeline.yml
    - ../group_vars/all/aap_httpd_pipeline.yml
    - ../group_vars/all/aap_apache_stack_pipeline.yml
    - ../group_vars/all/aap_vm_cpu_modification_pipeline.yml
    - ../group_vars/all/aap_vm_memory_modification_pipeline.yml
    - ../group_vars/all/aap_apache_troubleshoot_pipeline.yml
    - ../group_vars/all/aap_lightspeed_remediation_pipeline.yml
    - ../group_vars/all/aap_eda_pipeline.yml
    - ../group_vars/all/observability_kit.yml
    - ../group_vars/all/gitops_observability.yml
    - ../group_vars/all/openshift_apache_monitoring.yml
  tasks:
    - ansible.builtin.import_role:
        name: demo_platform
        tasks_from: uninstall_main
