---
- name: Configure AAP VM provisioning workflow
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../../group_vars/all/aap_vm_pipeline.yml
    - ../../group_vars/all/itsm_generic_app_stack.yml
  roles:
    - role: aap_vm_pipeline
