---
- name: Configure AAP AIOps organization and credentials
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../../group_vars/all/aap_casc.yml
  vars:
    demo_platform_artifacts_dir: "{{ playbook_dir }}/../../artifacts"
    aap_casc_artifact_file: "{{ demo_platform_artifacts_dir }}/demo_platform_facts.yml"
  tasks:
    - name: Configure AAP CASC resources
      ansible.builtin.include_role:
        name: aap_casc
