---
- name: Configure Event-Driven Ansible Apache alert pipeline
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../../group_vars/all/aap_eda_pipeline.yml
    - ../../group_vars/all/observability_kit.yml
  roles:
    - role: aap_eda_pipeline
