---
- name: Configure Event-Driven Ansible Generic Application alert pipeline
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../../group_vars/all/aap_eda_pipeline.yml
  vars:
    aap_eda_pipeline_artifacts_file: "{{ playbook_dir }}/../../artifacts/demo_platform_facts.yml"
  roles:
    - role: aap_eda_pipeline
