---
- name: Configure AAP Apache httpd deployment workflow
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../../group_vars/all/aap_httpd_pipeline.yml
    - ../../group_vars/all/itsm_apache_stack.yml
  roles:
    - role: aap_httpd_pipeline
