---
- name: Remove custom credential types from AAP
  awx.awx.credential_type:
    name: "{{ item }}"
    kind: cloud
    state: absent
    controller_host: "{{ aap_uninstall_controller_host }}"
    controller_oauthtoken: "{{ aap_uninstall_controller_oauthtoken }}"
    validate_certs: "{{ aap_uninstall_validate_certs }}"
  loop:
    - "{{ aap_uninstall_credential_type_chat }}"
    - "{{ aap_uninstall_credential_type_gitea }}"
    - "{{ aap_uninstall_credential_type_gitops }}"
    - "{{ aap_uninstall_credential_type_itsm }}"
