---
- name: Remove Generic Application deployment pipeline job templates from AAP
  awx.awx.job_template:
    name: "{{ item }}"
    organization: "{{ aap_generic_app_pipeline_organization }}"
    state: absent
    controller_host: "{{ aap_uninstall_controller_host }}"
    controller_oauthtoken: "{{ aap_uninstall_controller_oauthtoken }}"
    validate_certs: "{{ aap_uninstall_validate_certs }}"
  loop:
    - "{{ aap_generic_app_pipeline_jt_install }}"
    - "{{ aap_generic_app_pipeline_jt_deploy }}"
    - "{{ aap_generic_app_pipeline_jt_expose }}"
    - "{{ aap_generic_app_pipeline_jt_register_itsm }}"
    - "{{ aap_generic_app_pipeline_jt_start }}"

- name: Remove Generic Application alert incident job template from AAP
  awx.awx.job_template:
    name: "{{ aap_eda_pipeline_jt_create_incident }}"
    organization: "{{ aap_eda_pipeline_incident_jt_organization }}"
    state: absent
    controller_host: "{{ aap_uninstall_controller_host }}"
    controller_oauthtoken: "{{ aap_uninstall_controller_oauthtoken }}"
    validate_certs: "{{ aap_uninstall_validate_certs }}"
  ignore_errors: true

- name: Remove Generic Application stack pipeline job templates from AAP
  awx.awx.job_template:
    name: "{{ item }}"
    organization: "{{ aap_generic_app_stack_pipeline_organization }}"
    state: absent
    controller_host: "{{ aap_uninstall_controller_host }}"
    controller_oauthtoken: "{{ aap_uninstall_controller_oauthtoken }}"
    validate_certs: "{{ aap_uninstall_validate_certs }}"
  loop:
    - "{{ aap_generic_app_stack_pipeline_jt_submit_itsm_request }}"
    - "{{ aap_generic_app_stack_pipeline_jt_resolve_vars }}"
    - "{{ aap_generic_app_stack_pipeline_jt_remediate_incident }}"

- name: Remove Generic Application stack delete pipeline job templates from AAP
  awx.awx.job_template:
    name: "{{ item }}"
    organization: "{{ aap_generic_app_delete_pipeline_organization }}"
    state: absent
    controller_host: "{{ aap_uninstall_controller_host }}"
    controller_oauthtoken: "{{ aap_uninstall_controller_oauthtoken }}"
    validate_certs: "{{ aap_uninstall_validate_certs }}"
  loop:
    - "{{ aap_generic_app_delete_pipeline_jt_delete_probe }}"
    - "{{ aap_generic_app_delete_pipeline_jt_delete_manifest }}"
    - "{{ aap_generic_app_delete_pipeline_jt_delete_itsm_app }}"
    - "{{ aap_generic_app_delete_pipeline_jt_delete_itsm_vm }}"
