---
- name: List gateway organizations to find AIOps
  ansible.builtin.uri:
    url: >-
      {{ aap_uninstall_controller_host }}/api/gateway/v1/organizations/?name={{
      aap_uninstall_organization | urlencode }}
    method: GET
    headers:
      Authorization: "Bearer {{ aap_uninstall_controller_oauthtoken }}"
    validate_certs: "{{ aap_uninstall_validate_certs }}"
    status_code: 200
  register: aap_uninstall_gateway_orgs

- name: Delete AIOps organization from AAP gateway
  ansible.builtin.uri:
    url: >-
      {{ aap_uninstall_controller_host }}/api/gateway/v1/organizations/{{
      aap_uninstall_gateway_orgs.json.results[0].id }}/
    method: DELETE
    headers:
      Authorization: "Bearer {{ aap_uninstall_controller_oauthtoken }}"
    validate_certs: "{{ aap_uninstall_validate_certs }}"
    status_code: [202, 204]
  when: aap_uninstall_gateway_orgs.json.count | default(0) > 0

- name: Wait for AIOps organization to disappear from controller API
  ansible.builtin.uri:
    url: >-
      {{ aap_uninstall_controller_host }}/api/controller/v2/organizations/?name={{
      aap_uninstall_organization | urlencode }}
    method: GET
    headers:
      Authorization: "Bearer {{ aap_uninstall_controller_oauthtoken }}"
    validate_certs: "{{ aap_uninstall_validate_certs }}"
    status_code: 200
  register: aap_uninstall_controller_orgs
  until: aap_uninstall_controller_orgs.json.count | default(0) == 0
  retries: 15
  delay: 2
  when: aap_uninstall_gateway_orgs.json.count | default(0) > 0
