---
- name: Remove EDA resources for Apache alert pipeline
  ansible.builtin.include_tasks: eda_resources.yml

- name: Remove workflow job templates
  ansible.builtin.include_tasks: workflows.yml

- name: Remove job templates
  ansible.builtin.include_tasks: job_templates.yml

- name: Remove AIOps Playbooks project
  ansible.builtin.include_tasks: project.yml

- name: Remove inventories
  ansible.builtin.include_tasks: inventories.yml

- name: Remove credentials
  ansible.builtin.include_tasks: credentials.yml

- name: Remove AIOps organization
  ansible.builtin.include_tasks: organization.yml

- name: Remove custom credential types
  ansible.builtin.include_tasks: credential_types.yml
  when: uninstall_aap_remove_credential_types | bool
