---
- name: Remove legacy Apache stack workflow job templates from AAP
  awx.awx.workflow_job_template:
    name: "{{ item }}"
    organization: "{{ aap_uninstall_organization }}"
    state: absent
    controller_host: "{{ aap_uninstall_controller_host }}"
    controller_oauthtoken: "{{ aap_uninstall_controller_oauthtoken }}"
    validate_certs: "{{ aap_uninstall_validate_certs }}"
  loop: "{{ aap_uninstall_legacy_apache_stack_workflows | default([]) }}"
  when: aap_uninstall_legacy_apache_stack_workflows | default([]) | length > 0

- name: Remove legacy Apache stack job templates from AAP
  awx.awx.job_template:
    name: "{{ item }}"
    organization: "{{ aap_uninstall_organization }}"
    state: absent
    controller_host: "{{ aap_uninstall_controller_host }}"
    controller_oauthtoken: "{{ aap_uninstall_controller_oauthtoken }}"
    validate_certs: "{{ aap_uninstall_validate_certs }}"
  loop: "{{ aap_uninstall_legacy_apache_stack_job_templates | default([]) }}"
  when: aap_uninstall_legacy_apache_stack_job_templates | default([]) | length > 0

- name: Remove Deploy Generic Application Stack master workflow from AAP
  awx.awx.workflow_job_template:
    name: "{{ aap_apache_stack_pipeline_workflow }}"
    organization: "{{ aap_uninstall_organization }}"
    state: absent
    controller_host: "{{ aap_uninstall_controller_host }}"
    controller_oauthtoken: "{{ aap_uninstall_controller_oauthtoken }}"
    validate_certs: "{{ aap_uninstall_validate_certs }}"

- name: Remove Deploy Generic App workflow job template from AAP
  awx.awx.workflow_job_template:
    name: "{{ aap_httpd_pipeline_workflow }}"
    organization: "{{ aap_uninstall_organization }}"
    state: absent
    controller_host: "{{ aap_uninstall_controller_host }}"
    controller_oauthtoken: "{{ aap_uninstall_controller_oauthtoken }}"
    validate_certs: "{{ aap_uninstall_validate_certs }}"

- name: Remove Provision VM workflow job template from AAP
  awx.awx.workflow_job_template:
    name: "{{ aap_vm_pipeline_workflow }}"
    organization: "{{ aap_uninstall_organization }}"
    state: absent
    controller_host: "{{ aap_uninstall_controller_host }}"
    controller_oauthtoken: "{{ aap_uninstall_controller_oauthtoken }}"
    validate_certs: "{{ aap_uninstall_validate_certs }}"

- name: Remove Modify VM CPUs workflow job template from AAP
  awx.awx.workflow_job_template:
    name: "{{ aap_vm_cpu_modification_pipeline_workflow }}"
    organization: "{{ aap_uninstall_organization }}"
    state: absent
    controller_host: "{{ aap_uninstall_controller_host }}"
    controller_oauthtoken: "{{ aap_uninstall_controller_oauthtoken }}"
    validate_certs: "{{ aap_uninstall_validate_certs }}"

- name: Remove Modify VM Memory workflow job template from AAP
  awx.awx.workflow_job_template:
    name: "{{ aap_vm_memory_modification_pipeline_workflow }}"
    organization: "{{ aap_uninstall_organization }}"
    state: absent
    controller_host: "{{ aap_uninstall_controller_host }}"
    controller_oauthtoken: "{{ aap_uninstall_controller_oauthtoken }}"
    validate_certs: "{{ aap_uninstall_validate_certs }}"

- name: Remove Lightspeed Remediation workflow job template from AAP
  awx.awx.workflow_job_template:
    name: "{{ aap_lightspeed_remediation_pipeline_workflow }}"
    organization: "{{ aap_uninstall_organization }}"
    state: absent
    controller_host: "{{ aap_uninstall_controller_host }}"
    controller_oauthtoken: "{{ aap_uninstall_controller_oauthtoken }}"
    validate_certs: "{{ aap_uninstall_validate_certs }}"
